FROM debian:jessie-slim

RUN apt-get update -qq && \
    apt-get install -qqy --no-install-recommends\
      ca-certificates \
      curl \
      apt-transport-https \
      lsb-release \
      gnupg &&\
    curl -sL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor | tee /etc/apt/trusted.gpg.d/microsoft.gpg > /dev/null && \
    AZ_REPO=$(lsb_release -cs) && echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" | tee /etc/apt/sources.list.d/azure-cli.list && \
    apt-get update -qq && \
    apt-get install azure-cli && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /work
ENV EDITOR vim
CMD ["/bin/sh"]